
@port = 3000

###
POST http://localhost:{{port}}/getMaterias
Content-Type: application/json

{
 "id_user": "UNZRHNqON8ZUjhT0xK9E"
}

###
POST http://localhost:{{port}}/addMateria
Content-Type: application/json

{
 "id_user": "UNZRHNqON8ZUjhT0xK9E", 
"nome": "teste3", 
"semana": 4, 
"faltas": 5
}

###
POST http://localhost:{{port}}/editMateria
Content-Type: application/json

{
    "id_materia": "1WYHoKvYrsqkZkUkktly",
    "nome": "teste344", 
    "semana": 4, 
    "faltas": 5,
    "faltas_active": 3
}

###
POST http://localhost:{{port}}/deleteMateria
Content-Type: application/json

{
    "id_materia": "rHs2Ar7q0OrppTcTavby"
}

###
POST http://localhost:{{port}}/activeFalta
Content-Type: application/json

{
   "indice": 6, 
   "active": true, 
   "id_materia": "9CTFQuOftjWRaSyGJXJO"  
}